version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    container_name: production_web
    ports:
      - 9000:80
    environment:
      - ENV=production
      - NODE_ENV=production